# Jekyll config

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en"
title                    : "Sean Ho"
title_separator          : "-"
name                     : "Sean Ho"
description              : "Homepage of Dr. Sean Ho"
url                      : "https://seanho.com"
baseurl                  : 
repository               : "seanho00/seanho00.github.io"
teaser                   : "assets/img/seanho-golden-ears.jpg"
breadcrumbs              : false
words_per_minute         : 200

# SEO Related
google_site_verification : "xaOoNhR61z_EeaRqFgLi6faglR3IH2tHtB8xkpc8_PQ"
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : seanho
facebook:
  username               : seanho00
og_image                 : # Open Graph/Twitter default site image

# Analytics
analytics:
  provider               : false 
  google:
    tracking_id          :

# Site Author
author:
  name             : "Sean Ho"
  avatar           : "/assets/img/seanho-180.png"
  bio              : ""
  location         : "Vancouver, BC"
  email            : "www@seanho.com"
  uri              :
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : "seanho00"
  foursquare       :
  github           : "seanho00"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "seanho00"
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            : 
  tumblr           :
  twitter          : "seanho"
  vine             :
  weibo            :
  xing             :
  youtube          : # "https://youtube.com/c/MichaelRoseDesign"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Vancouver

# Jekyll Plugins
plugins:
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /cat/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
